version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
  - source: /style/
    destination: /var/www/html/style/
  - source: /js/bundle.js
    destination: /var/www/html/js/
  - source: /image/
    destination: /var/www/html/image/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
